![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np
import random

In [3]:
array = np.arange(0,10)
array[::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [4]:
print(array[::-1][1:3])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [5]:
print(array[::-1][7::])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [6]:
matriz = np.arange(1,21).reshape(4,5)
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [7]:
matriz_ivnertida = matriz[::-1,::-1]
print(matriz_ivnertida)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [8]:
a = matriz[0][0:2]
b = matriz[1][0:2]

np.vstack([a,b])

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [9]:
c = matriz[0][0::2]
d = matriz[2][0::2]
np.vstack([c,d])

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [10]:
e = matriz[0:3]
e[0::,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [11]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
loros = x[x == "Loro"]
print(loros)

['Loro' 'Loro']


In [12]:
indices_loros = np.where(x == "Loro")
loros = x[indices_loros]
print(loros)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [13]:
sec20 = np.random.randint(1,21, size= 20).reshape(2,5,2)
sec20

array([[[ 6, 18],
        [16, 17],
        [ 1,  2],
        [17, 15],
        [ 3, 15]],

       [[ 5, 11],
        [ 6, 19],
        [ 6, 20],
        [ 2,  6],
        [19,  4]]], dtype=int32)

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [14]:
np.flip(matriz)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [15]:
zeros = np.zeros(10)
print(zeros)
print(f'Bytes: {zeros.nbytes}')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Bytes: 80


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [16]:
vec2 = np.arange(10,50).reshape(20,2)
print(vec2)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]
 [40 41]
 [42 43]
 [44 45]
 [46 47]
 [48 49]]


In [17]:
np.flip(vec2)

array([[49, 48],
       [47, 46],
       [45, 44],
       [43, 42],
       [41, 40],
       [39, 38],
       [37, 36],
       [35, 34],
       [33, 32],
       [31, 30],
       [29, 28],
       [27, 26],
       [25, 24],
       [23, 22],
       [21, 20],
       [19, 18],
       [17, 16],
       [15, 14],
       [13, 12],
       [11, 10]])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [18]:
array = np.array([1,2,0,0,4,0])
np.nonzero(array)

(array([0, 1, 4]),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [19]:
np.random.seed(0)
a = np.random.randint(1,3000,size=100).reshape(10,10)
print(a)
print(f'minimo: {np.min(a)}')
print(f'maximo: {np.max(a)}')

[[2733 2608 1654  836  764 1732 1034  278 1779 1829]
 [2648 2649 2363  706 2600 2136 2223 2898 1702  538]
 [2894 2121 2826 1941 2164  977  756 2047 1872 2497]
 [2899  100 2009  756  798  660 2959  424 2746  640]
 [ 545 2592  715 2293  152 2724 2559 2931 1208 2077]
 [ 803 2177 2177 1957 1926  757  274 2384  389 1642]
 [1467 2592  889  258 1346 2106 2340 2828  431   92]
 [1921 2447 2660 1590 2957 2682   85 2252  325  775]
 [1072  640 2037 1156  973 2917 1205 2025 1168 1685]
 [2840 2768 2958  374 1878  561 1330 1606 2218 1700]]
minimo: 85
maximo: 2959


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [20]:
vector = np.random.randint(1,300,size=30).reshape(5,6)
media = np.mean(vector)

print(vector)
print(f'Media: {media}')

[[ 96 198  95 257 179 293]
 [ 99  43 202   1  44  24]
 [188 131  99  63 223 124]
 [ 83 228 149 210  51 271]
 [ 42  59 194  37 267  87]]
Media: 134.56666666666666


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [21]:
uno_zeros = np.zeros(25).reshape(5,5)
uno_zeros[0] = 1
uno_zeros[-1] = 1
uno_zeros[:,0] = 1
uno_zeros[:,-1] = 1

print(uno_zeros)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [24]:
tab = np.zeros((8, 8),dtype=int)
tab[::2, 1::2] = 1  
tab[1::2, ::2] = 1  

print(tab)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [23]:
unos_ceros = np.array([[0, 1], [1, 0]])
zx = np.tile(unos_ceros, (4, 4))

print(zx)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.