![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [2]:
import numpy as np
import random

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [3]:
my_array = np.array(range(0,10))
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [4]:
random.seed(0)
array_t = np.random.randint(10, size=(3,3)) 
array_t

array([[3, 5, 4],
       [1, 0, 6],
       [3, 2, 1]], dtype=int32)

In [5]:
array_t > 0

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [6]:
impares = my_array[my_array % 2!= 0]
np.copy(my_array)
impares

array([1, 3, 5, 7, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [7]:
my_array[my_array % 2!= 0] = -1
nuevo = my_array
print(nuevo)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [8]:
my_array
c = my_array % 2 != 0
c = np.where(c, -1, my_array)
c


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [9]:
my_array.reshape(1,-1)


array([[ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
```

In [10]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate((a, b), axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [11]:
# np.concatenate((a, b), axis=1)
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [12]:
c = np.array([1,2,3,2,3,4,3,4,5,6])
d = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(c, d)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [13]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [14]:
array_por_10 = my_array.dot(10)
print(f' La nueva array * 10:  {array_por_10}')
print(f'Primer elemento:       {array_por_10[0]}')
print(f'ultimo elemento:       {array_por_10[-1]}')
print(f'Elementos del 1 al 7:  {array_por_10[1:8]}')

 La nueva array * 10:  [  0 -10  20 -10  40 -10  60 -10  80 -10]
Primer elemento:       0
ultimo elemento:       -10
Elementos del 1 al 7:  [-10  20 -10  40 -10  60 -10]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [15]:
my_matrix = np.random.randint(1,10, size=9).reshape(3,3)
my_matrix

array([[5, 8, 9],
       [7, 8, 7],
       [1, 6, 7]], dtype=int32)

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [16]:
new_array = np.arange(1,50,3)
new_array

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [17]:
new_array = np.linspace(4.0, 1.25, num=12)
new_array

array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ,
       1.25])

## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [18]:
array_nuevo = np.arange(1,5).reshape(4,1)
print(array_nuevo)

array_nuevo.reshape(2,2)

[[1]
 [2]
 [3]
 [4]]


array([[1, 2],
       [3, 4]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [19]:
secuencia = np.random.randint(15, size = (4,5,3))
secuencia

array([[[ 3, 10, 14],
        [ 7, 11,  5],
        [12,  7,  9],
        [ 4,  3,  5],
        [ 1,  8,  8]],

       [[ 6,  2,  3],
        [10,  4,  8],
        [12,  3,  4],
        [ 2,  2,  5],
        [ 0, 10,  4]],

       [[ 2,  0,  5],
        [10,  7,  5],
        [12,  5,  2],
        [ 9,  4,  0],
        [ 9,  7,  2]],

       [[ 1, 12, 10],
        [ 5, 12,  9],
        [ 2, 10,  5],
        [ 0, 10,  2],
        [ 1, 11, 10]]], dtype=int32)

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [20]:
f = np.zeros([10])
diez_1 = f > 1
diez_1.reshape(10,1)

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [21]:
diez_1.reshape(2,5)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [24]:
x =np.random.randint(10, 20, size = (5,2,6))
x

array([[[12, 15, 19, 11, 16, 12],
        [18, 19, 18, 16, 11, 16]],

       [[10, 17, 13, 17, 14, 12],
        [19, 10, 17, 19, 12, 12]],

       [[11, 12, 15, 14, 17, 10],
        [16, 13, 17, 17, 19, 16]],

       [[16, 17, 18, 17, 10, 18],
        [10, 12, 11, 13, 10, 19]],

       [[16, 13, 11, 10, 18, 12],
        [15, 13, 10, 18, 19, 18]]], dtype=int32)

In [23]:
print(x.size)
print(x.ndim)
print(x.shape)
y = x[0]
print(y.size)


60
3
(5, 2, 6)
12
